# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-04 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('cod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, upload_to=b'')),
                ('nombre', models.CharField(max_length=100)),
                ('cantdisponible', models.IntegerField()),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgpremio', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('mpoints', models.IntegerField()),
                ('nivel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PremiosObtenidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('premios', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Premios')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoMateriales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaprestamo', models.DateTimeField()),
                ('fechadevolucion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('D', 'Devuelto'), ('N', 'No Devuelto'), ('F', 'Devuelto con atraso')], max_length=1)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('introduccion', models.CharField(max_length=20000)),
                ('objetivo', models.CharField(max_length=5000)),
                ('descripcion', models.CharField(max_length=30000)),
                ('imgproyecto', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsabilidadesLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redsocial', models.BooleanField()),
                ('peventos', models.BooleanField()),
                ('eslider', models.BooleanField()),
                ('nivelproyecto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=60)),
                ('agedate', models.DateField()),
                ('mpoints', models.IntegerField()),
                ('estado', models.CharField(max_length=25)),
                ('imgpath', models.ImageField(upload_to=b'')),
                ('premios', models.ManyToManyField(to='api.PremiosObtenidos')),
                ('responsabilidades', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ResponsabilidadesLevel')),
            ],
        ),
        migrations.AddField(
            model_name='proyectos',
            name='integrantes',
            field=models.ManyToManyField(to='api.Usuario'),
        ),
        migrations.AddField(
            model_name='prestamomateriales',
            name='usuario',
            field=models.ManyToManyField(to='api.Usuario'),
        ),
        migrations.AddField(
            model_name='materiales',
            name='prestamos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PrestamoMateriales'),
        ),
    ]
