# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-04 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiosobtenidos',
            name='premios',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='premios',
        ),
        migrations.AddField(
            model_name='premiosobtenidos',
            name='imgpremio',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='premiosobtenidos',
            name='nombre',
            field=models.CharField(default='SIN PREMIO', max_length=20),
        ),
        migrations.AddField(
            model_name='premiosobtenidos',
            name='usuario',
            field=models.ForeignKey(default='sin usuario', on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('I', 'Integrante')], default='I', max_length=20),
        ),
        migrations.AlterField(
            model_name='premios',
            name='imgpremio',
            field=models.ImageField(upload_to=b''),
        ),
    ]
