# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-04 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200504_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiosobtenidos',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='premiosobtenidos',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='premiosobtenidos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('I', 'Integrante')], max_length=20),
        ),
    ]
