# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-04 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200504_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
