# Generated by Django 3.0.5 on 2020-09-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=200)),
                ('descripcion', models.CharField(default=None, max_length=1000)),
                ('código', models.CharField(default=None, max_length=10)),
                ('estaPrestado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=100)),
                ('imagenProject', models.ImageField(upload_to='')),
                ('scoreRequired', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TblUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('imgUser', models.ImageField(blank=True, null=True, upload_to='media/perfil/', verbose_name='Imagen de Perfil')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_activo', models.BooleanField(default=False)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('P', 'Presidente'), ('VP', 'Vicepresidente'), ('S', 'Secretario'), ('T', 'Tesorero'), ('C', 'Cordinador'), ('SN', 'Senior'), ('I', 'Integrante')], default='I', max_length=40)),
                ('activo', models.BooleanField(default=False)),
                ('scoreActivity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, max_length=200)),
                ('descripcion', models.CharField(default=None, max_length=1000)),
                ('mentor', models.CharField(default=None, max_length=100)),
                ('Consultor', models.CharField(default=None, max_length=100)),
                ('Equipo', models.CharField(default=None, max_length=400)),
                ('imagenProject', models.ImageField(upload_to='')),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appcmback.TblUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='PremiosObtenidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idPremio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcmback.Premio')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcmback.TblUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialesPrestados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idMaterial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcmback.Materiales')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcmback.TblUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, max_length=200)),
                ('descripcion', models.CharField(default=None, max_length=1000)),
                ('fecha', models.DateField()),
                ('imagenProject', models.ImageField(upload_to='')),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appcmback.TblUsuario')),
            ],
        ),
    ]
