# Generated by Django 3.0.5 on 2020-09-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcmback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='eventos',
            name='idUsuario',
            field=models.ManyToManyField(to='appcmback.TblUsuario'),
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='idUsuario',
            field=models.ManyToManyField(to='appcmback.TblUsuario'),
        ),
    ]
